docs/deploy-gh-pages.sh

Don't fail CI, when docs are up to date

Stabilize Pages CI

---

bot/registration.py

Improve formatting of registration request message

---

bot/editing.py

Fix birthday not addable

---

components/member.py

* Fix locale issue with March
* Try getting rid of pandas warnings

Improve Member._get_akadressen()

---

bot/editing.py

Turns out it was just a wrongly set kwarg …
Closes #11

Show text along with current user picture

---

bot/error.py

Improve error handler

---

bot/highscore.py

* Only 10 instead of 25 members on the highscore
* Buttons not all in one column

Improve highscore layout

---

bot/editing.py
bot/registration.py
bot/setup.py
components/member.py
components/orchestra.py
components/question.py
components/types.py
tests/test_member.py

Photo -> Foto

---

bot/check_user_status.py

Fix check_user_status

---

bot/inline.py

Allow admins to see all data through inline mode

---

bot/editing.py

fix different bugs in the editing conversation
closes #30

Fix editing conversation

---

bot/highscore.py
components/userscore.py
tests/test_userscore.py

Fix highscore

---

bot/__init__.py
bot/constants.py
bot/game.py
bot/keyboards.py
components/__init__.py
components/attributemanager.py
components/orchestra.py
components/questioner.py
tests/test_attributemanager.py
tests/test_orchestra.py
tests/test_questioner.py

* Fixes logic gaps behind `Orchestra.questionable()`
* Adjusts game setup conversation accordingly
* Also in the question selection step, options are shown depending on hint selection making the setup smoother
Closes #27

Overhaul AttributeManagers and Game Setup

---

bot/setup.py
docs/source/faq.rst
docs/source/privacy.rst
requirements.txt

Add statistics

---

bot/game.py
bot/keyboards.py
components/attributemanager.py
components/orchestra.py
components/questioner.py
tests/test_attributemanager.py
tests/test_orchestra.py

Exlude Player from Possible Hints

---

bot/game.py

Allow interrupting free text games

---

components/member.py

Add conductor to allowed instruments

---

components/attributemanager.py
components/orchestra.py
tests/test_attributemanager.py
tests/test_orchestra.py

Use deepcopy instead of copy for Members

---

bot/registration.py

Handle users blocking the bot before admin can handle registration request
Closes #51

Stabalize Registration Process

---

bot/editing.py
bot/registration.py

Move fetching TG profile pic to editing conversation

---

bot/editing.py
components/helpers.py
components/member.py
components/question.py
docs/source/faq.rst
tests/test_question.py

* makes sure to strip "Germany" from address even, if no housenumber is present
* allows to pass coordinates as text for setting address and as free text answer
* adds documentation
closes #57

Improve parsing of addresses

---

components/attributemanager.py

Apparently pickle doesn't care about strings being immutable …
closes #58 again

Check gender by equality in AMs instead of identity

---

components/member.py

Fix vcard for no housnumber

---

bot/inline.py
bot/registration.py
components/member.py
tests/test_member.py

* Allow admin to request all vcards
* 10 results per page
* emtpy query lists all members alphabetically
* Fix security bug allowing non-registered users to access inline mode

Overhaul contact requests

---

components/orchestra.py
tests/test_orchestra.py

Don't show 0-entries in highscore

---

bot/game.py
bot/keyboards.py

Save last GameSettings and tweak "Alle" button

---

bot/game.py

fix saving game settings

---

bot/editing.py

Accept no landscape pictures; require portrait or square

---

components/member.py

Fix reading of birth year

---

components/member.py
components/question.py
tests/test_question.py

Increase difficulty for address and names

---

bot/__init__.py
bot/ban.py
bot/cancel_membership.py
bot/constants.py
bot/editing.py
bot/game.py
bot/setup.py

For the few use cases where a user can produce an error by not properly closing a conversation.
Closes #79

Check conversation status before processing update

---

bot.ini
bot/backup.py
bot/setup.py
docs/source/bot.backup.rst
docs/source/bot.rst
docs/source/hosting.rst
requirements.txt

Create nightly backups to nextcloud

---

bot/__init__.py
bot/backup.py
bot/setup.py
components/member.py
main.py
tests/test_member.py

Reads all the config data in `main` and hands it to `setup`, where it's applied. That's cleaner than reading from the config within the classes/methods

Refactor config handling

---

components/orchestra.py
tests/test_orchestra.py

Compare orchestras as False

---

bot.ini
bot/constants.py
bot/editing.py
bot/setup.py
bot/yourls.py
docs/source/bot.rst
docs/source/bot.yourls.rst
main.py
requirements.txt

Prepare mail to board after editing details

---

bot/backup.py
bot/check_user_status.py
bot/editing.py
bot/error.py
bot/inline.py
bot/setup.py
components/member.py
components/orchestra.py
components/userscore.py
main.py
requirements.txt
tests/orchestra.py
tests/test_attributemanager.py
tests/test_member.py
tests/test_orchestra.py
tests/test_questioner.py
tests/test_userscore.py

Update PTB to v13.3

---

.github/CONTRIBUTING.rst
bot/cancel_membership.py
bot/commands.py

fixed typos, #107
